### ISSUE TITLE
USER STORY: Collecting users' feedback

### ISSUE THREAD

**Issue by dandon1990** [dandon1990/My-First-Agile-Project#3]
In order to **to collect users feedback** as a **administrator**, I can **publish a poll**

# Acceptance Criteria

* Options will be provided as check boxes 
* Check box should be checked as default
* Options will be next to submit button
* Poll should disappear 2 days after posting

# Tasks
- [ ] Update the view: Creating poll (HTML & CSS)
- [ ] Update the view: Create countdown to when the poll ends
- [ ] Create JavaScript function to remove poll 2 days after countdown ends
- [ ] Test functionality
